# Generated by Django 4.0.4 on 2022-04-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='default.jpg', upload_to='posters'),
        ),
    ]
